# Generated by Django 4.0.3 on 2022-08-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_tel_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/users'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subrole',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
