# Generated by Django 4.1 on 2022-08-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_role_alter_customuser_subrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(max_length=128, unique=True, verbose_name='email'),
        ),
    ]
