# Generated by Django 4.0.3 on 2022-08-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('utilisateur', 'Utilisateur générique'), ('gestionaire', "Gestionaire d'école")], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subrole',
            field=models.CharField(blank=True, choices=[('admin', 'School Admin'), ('editor', 'School Editor')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
