# Generated by Django 4.1 on 2022-08-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='anon.jpg', null=True, upload_to='users'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
