# Generated by Django 4.1 on 2022-08-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_image_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='anonuser.jpg', null=True, upload_to='users'),
        ),
    ]
