# Generated by Django 4.1 on 2022-09-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('generic', 'Parent/Eleve'), ('teacher', 'Enseignant'), ('manager', "Gestionaire d'école")], max_length=50, null=True),
        ),
    ]
