# Generated by Django 4.0.3 on 2022-08-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('title', models.CharField(default='News Title', max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, default='News')),
                ('date_posted', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
