# Generated by Django 4.0.3 on 2022-08-04 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EduLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('tel', models.CharField(default='00-00-00-00', max_length=255)),
                ('cel', models.CharField(default='00-00-00-00', max_length=255)),
                ('moto', models.CharField(default='slogan', max_length=255)),
                ('year_founded', models.CharField(max_length=4)),
                ('history', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('teacher_count', models.IntegerField(default='0')),
                ('student_count', models.IntegerField(default='0')),
                ('classe_count', models.IntegerField(default='0')),
                ('lab_count', models.IntegerField(default='0')),
                ('success_rate', models.IntegerField(default='0')),
                ('is_featured', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='schools/thumbnails')),
                ('crest', models.ImageField(blank=True, null=True, upload_to='schools/crests')),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('edu_levels', models.ManyToManyField(to='schools.edulevel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='schools/images', verbose_name='Image')),
                ('listing', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
    ]
