# Generated by Django 4.0.3 on 2022-08-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='classe_count',
            new_name='classes',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='lab_count',
            new_name='labs',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='student_count',
            new_name='students',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='teacher_count',
            new_name='teachers',
        ),
        migrations.AddField(
            model_name='school',
            name='curriculums',
            field=models.IntegerField(default='0'),
        ),
    ]
