# Generated by Django 4.0.3 on 2022-08-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_rename_classe_count_school_classes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='faculties',
            field=models.IntegerField(default='0'),
        ),
    ]
