# Generated by Django 4.0.3 on 2022-08-04 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_faculties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='listing',
            new_name='school',
        ),
        migrations.RemoveField(
            model_name='school',
            name='teachers',
        ),
        migrations.AddField(
            model_name='school',
            name='advantages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='availability',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='awards',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='canteens',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='school',
            name='courses',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='diplomas',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(default='example@school.com', max_length=254),
        ),
        migrations.AddField(
            model_name='school',
            name='mgt_quote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='resumption',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='school',
            name='staff',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='school',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default='0')),
                ('fullname', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='schools/teachers', verbose_name='Image')),
                ('facebook', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('school', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='year', max_length=4)),
                ('pass_rate', models.IntegerField(default='0')),
                ('fail_rate', models.IntegerField(default='0')),
                ('school', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
    ]
