# Generated by Django 4.0.3 on 2022-08-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_rename_listing_images_school_remove_school_teachers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='canteens',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='classes',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='curriculums',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='edu_levels',
            field=models.ManyToManyField(null=True, to='schools.edulevel'),
        ),
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.EmailField(default='example@school.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='faculties',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='labs',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='resumption',
            field=models.CharField(default='', max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='staff',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='students',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='success_rate',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='year_founded',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
