# Generated by Django 4.0.3 on 2022-08-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_alter_school_address_alter_school_canteens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='price_range',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='time_range',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
