# Generated by Django 4.0.3 on 2022-08-04 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_school_price_range_school_time_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default='0')),
                ('fullname', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('qualifications', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='schools/teachers', verbose_name='Image')),
                ('facebook', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Stats',
            new_name='Stat',
        ),
        migrations.AlterField(
            model_name='school',
            name='courses',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='diplomas',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
    ]
