# Generated by Django 4.0.3 on 2022-08-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_teacher_rename_stats_stat_alter_school_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='libs',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='edu_levels',
            field=models.ManyToManyField(to='schools.edulevel'),
        ),
    ]
