# Generated by Django 4.0.3 on 2022-08-04 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_school_libs_alter_school_edu_levels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='advantages',
            new_name='ad_copy',
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255, null=True)),
                ('school', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
    ]
