# Generated by Django 4.0.3 on 2022-08-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_rename_advantages_school_ad_copy_advantage'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='pedagogy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='phrase',
            field=models.CharField(default='avantage', max_length=255),
        ),
    ]
