# Generated by Django 4.1 on 2022-08-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_report_delete_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
