# Generated by Django 4.0.3 on 2022-08-07 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_alter_report_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='schools/photos')),
                ('school', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
