# Generated by Django 4.0.3 on 2022-08-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_photo_delete_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.CharField(default='maths', max_length=255),
            preserve_default=False,
        ),
    ]
