# Generated by Django 4.0.3 on 2022-08-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0019_teacher_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='fee',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='seats',
            field=models.IntegerField(default='0'),
        ),
    ]
