# Generated by Django 4.0.3 on 2022-08-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0020_classroom_fee_classroom_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='seats',
            new_name='maxseats',
        ),
        migrations.RemoveField(
            model_name='school',
            name='edu_levels',
        ),
        migrations.AddField(
            model_name='canteen',
            name='maxseats',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='vacant_seats',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='maxseats',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='library',
            name='maxseats',
            field=models.IntegerField(default='0'),
        ),
    ]
