# Generated by Django 4.0.3 on 2022-08-13 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0024_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='name',
        ),
    ]
