# Generated by Django 4.0.3 on 2022-08-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0028_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='duration',
            field=models.CharField(choices=[('undefined', 'Indefini'), ('month', 'Mois'), ('trimester', 'Trimestre'), ('semester', 'Semestre'), ('year', 'Annuel')], default='month', max_length=50, null=True),
        ),
    ]
