# Generated by Django 4.0.3 on 2022-08-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0029_alter_subscription_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='duration',
            field=models.CharField(choices=[('undefined', 'Indéfini'), ('month', 'Mois'), ('trimester', 'Trimestre'), ('semester', 'Semestre'), ('year', 'Année')], default='undefined', max_length=50, null=True),
        ),
    ]
