# Generated by Django 4.0.3 on 2022-08-13 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0030_alter_subscription_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(default='', max_length=255)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.subscription')),
            ],
        ),
    ]
