# Generated by Django 4.0.3 on 2022-08-13 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0031_subperk'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.subscription'),
        ),
    ]
