# Generated by Django 4.0.3 on 2022-08-13 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0032_school_subscription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubPerk',
            new_name='SubscriptionPerk',
        ),
    ]
