# Generated by Django 4.0.3 on 2022-08-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0034_remove_classroom_label_classroom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='fee',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='maxseats',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='vacant_seats',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
