# Generated by Django 4.1 on 2022-08-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0036_rename_vacant_seats_classroom_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='inscription',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
