# Generated by Django 4.1 on 2022-08-17 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0037_school_inscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='slug',
        ),
    ]
