# Generated by Django 4.1 on 2022-08-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0038_remove_school_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='tel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='cel',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='tel',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
