# Generated by Django 4.1 on 2022-08-24 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0039_teacher_tel_alter_school_cel_alter_school_tel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='edu_levels',
            new_name='levels',
        ),
    ]
