# Generated by Django 4.1 on 2022-08-25 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0040_rename_edu_levels_school_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='subscription',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.subscription'),
        ),
    ]
