# Generated by Django 4.1 on 2022-08-28 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0041_alter_school_subscription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='Plan',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='user',
            new_name='manager',
        ),
        migrations.RemoveField(
            model_name='school',
            name='subscription',
        ),
        migrations.DeleteModel(
            name='SubscriptionPerk',
        ),
    ]
