# Generated by Django 4.1 on 2022-08-28 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0043_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='subscription',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.plan'),
        ),
    ]
