# Generated by Django 4.1 on 2022-08-29 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0044_school_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='subscription',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schools.plan'),
        ),
    ]
