# Generated by Django 4.1 on 2022-08-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0046_subscription_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='name',
        ),
    ]
