# Generated by Django 4.1 on 2022-08-31 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0047_remove_subscription_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='is_featured',
        ),
    ]
