# Generated by Django 4.1 on 2022-09-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0049_alter_school_address_alter_school_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='Schblog',
        ),
        migrations.RemoveField(
            model_name='school',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='school',
            name='canteens',
        ),
        migrations.RemoveField(
            model_name='school',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='school',
            name='curriculums',
        ),
        migrations.RemoveField(
            model_name='school',
            name='diplomas',
        ),
        migrations.RemoveField(
            model_name='school',
            name='faculties',
        ),
        migrations.RemoveField(
            model_name='school',
            name='inscription',
        ),
        migrations.RemoveField(
            model_name='school',
            name='labs',
        ),
        migrations.RemoveField(
            model_name='school',
            name='libs',
        ),
        migrations.RemoveField(
            model_name='school',
            name='pedagogy',
        ),
        migrations.RemoveField(
            model_name='school',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='school',
            name='students',
        ),
    ]
