# Generated by Django 4.1 on 2022-09-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0051_rename_schblog_blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Article',
        ),
    ]
