# Generated by Django 4.1 on 2022-09-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0052_rename_blog_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='edu_levels',
            field=models.CharField(blank=True, choices=[('creche', 'Creche'), ('jardin', 'Jardin'), ('primaire', 'Primaire'), ('college', 'College'), ('lycee', 'Lycee'), ('universite', 'Universite'), ('centre-Academique', 'Centre-Academique'), ('centre-Professionnel', 'Centre-Professionnel')], max_length=144, null=True),
        ),
    ]
