# Generated by Django 4.1 on 2022-09-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0053_school_edu_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='edu_levels',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(choices=[('prof', 'Prof.'), ('doc', 'Doc.'), ('mr', 'M.'), ('mrs', 'Mme'), ('ms', 'Mlle')], default='undefined', max_length=50),
        ),
    ]
