# Generated by Django 4.1 on 2022-09-30 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0054_remove_school_edu_levels_alter_teacher_designation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='xp',
            new_name='years_of_experience',
        ),
    ]
