# Generated by Django 4.1 on 2022-09-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0056_structure_remove_laboratory_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='professors',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
