# Generated by Django 4.1 on 2022-10-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0059_rename_facebook_teacher_facebook_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
