# Generated by Django 4.1 on 2022-10-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0060_alter_article_content_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(choices=[('Prof.', 'Prof.'), ('Doc.', 'Doc.'), ('Mr.', 'M.'), ('Mrs.', 'Mme'), ('Ms.', 'Mlle')], default='', max_length=50),
        ),
    ]
