# Generated by Django 4.1 on 2022-10-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0061_alter_teacher_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='students',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
