# Generated by Django 4.1 on 2022-10-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0062_school_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='formations',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
