# Generated by Django 4.1 on 2022-08-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_advert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='role',
            new_name='ad_type',
        ),
    ]
