# Generated by Django 4.1 on 2022-08-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_role_advert_ad_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='ad_type',
            field=models.CharField(blank=True, choices=[('demand', 'Demande'), ('offer', 'Offre')], default='demand', max_length=50, null=True),
        ),
    ]
