# Generated by Django 4.1 on 2022-08-29 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_advert_telephone_alter_advert_ad_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='author',
        ),
        migrations.DeleteModel(
            name='Demand',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
